name: Pipeline CI - Testes de Software

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04 # Atualizado para evitar alertas do Ubuntu 26

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        # Instala as ferramentas de teste caso não estejam no seu requirements.txt
        pip install pytest pytest-cov 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Executar testes
      # O comando abaixo procura os testes automaticamente em qualquer pasta do projeto
      run: pytest --cov=. --cov-report=term-missing --cov-report=xml
